"""
Interactive tabs for the halohalo speech models, mounted inside the org
dashboard Space.

Three tabs, one per model family:
  Transcribe        every ASR model in asr_registry.json, pick per language
  Synthesize        speecht5_tts-pld-<lang>
  Convert voice     speecht5_vc-pld            (any-to-any, all ten languages)

Two constraints shape this file:

  - It shares a free CPU Space with the dashboard, so torch and transformers
    are imported *inside* the functions that need them. A missing or broken
    ML dependency then degrades these tabs rather than taking the dashboard
    down with it, and the Space still boots in seconds.
  - Models load lazily on first use and the ASR cache is two-tier: the bake-off
    added 1B CTC models (3.6 GB) and whisper-large-v3 (5.8 GB) to the 242M
    whisper-small models this tab used to serve alone, and two of the big ones
    resident at once would exhaust a free Space's RAM. See asr_model().

Speaker embeddings are precomputed (see prepare_space_assets.py in the
halohalo repo), so speechbrain is not a runtime dependency here.
"""

import json
from functools import lru_cache
from pathlib import Path

import gradio as gr
import numpy as np

ROOT = Path(__file__).parent
ORG = "sapinsapin"
SR = 16000
VC_MAXLENRATIO = 1.3       # ≈1.0x input duration; see convert()
DELIM = "|"                # CTC word delimiter, as in finetune_ctc.py

_assets_path = ROOT / "assets.json"
ASSETS = (json.loads(_assets_path.read_text(encoding="utf-8"))
          if _assets_path.exists() else {"languages": {}})
LANGS = ASSETS["languages"]
NAME_TO_CODE = {v["name"]: k for k, v in LANGS.items()}
CHOICES = [v["name"] for v in LANGS.values()]
DEFAULT = "Cebuano" if "Cebuano" in CHOICES else (CHOICES[0] if CHOICES else None)

VOICE_INDEX = {}
for _code, _meta in LANGS.items():
    for _v in _meta["voices"]:
        # carry the language so a conversion can be filed under it later
        VOICE_INDEX[f"{_meta['name']} · {_v['id']} ({_v['gender']})"] = {
            **_v, "language": _code}
VOICE_LABELS = list(VOICE_INDEX)


# ------------------------------------------------------------- ASR registry
#
# Which ASR models exist, what to load each with, and what its card claims.
# Generated by make_asr_registry.py; if it is missing the tab falls back to
# the one-model-per-language convention this demo shipped with, so a Space
# deployed without the file still transcribes.

_registry_path = ROOT / "asr_registry.json"
try:
    _REGISTRY = json.loads(_registry_path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError):
    _REGISTRY = {"as_of": None, "models": [
        {"repo": f"{ORG}/whisper-small-pld-{c}", "name": f"whisper-small-pld-{c}",
         "language": c, "kind": "whisper", "units": "bpe", "params": 242_000_000,
         "licence": "unknown", "base_model": "openai/whisper-small",
         "split": "in-domain"} for c in LANGS]}
REGISTRY_AS_OF = _REGISTRY.get("as_of")


def _label(m):
    """One line a person can choose between: family, size, and the headline
    error rate *with its split*, since in-domain and frozen-disjoint numbers
    for the same language differ by up to a factor of seven."""
    size = f"{(m['params'] or 0) / 1e6:.0f}M" if m.get("params") else "?"
    conv = " normalised" if m.get("normalised") else ""
    cer = f" · CER {m['cer'] * 100:.1f}% {m['split']}{conv}" if m.get("cer") else ""
    return f"{m['name']} · {size}{cer}"


# {language code: [model dict, ...]}. The language's own whisper-small
# baseline leads — it is what this tab served before there was a choice, and
# it is the fastest thing a free CPU Space can load — then smallest first.
MODELS = {}
# too big for this Space: named in the tab, never loaded (see
# make_asr_registry.MAX_WEIGHTS_GIB). A registry from before the flag existed
# has no `runnable` key, and everything in it was offered, so default to True.
TOO_BIG = [m for m in _REGISTRY["models"] if not m.get("runnable", True)]
for _m in _REGISTRY["models"]:
    if not _m.get("runnable", True):
        continue
    MODELS.setdefault(_m["language"], []).append(_m)
for _code in MODELS:
    MODELS[_code].sort(key=lambda m, c=_code: (
        m["name"] != f"whisper-small-pld-{c}", m.get("params") or 0, m["name"]))
MODEL_BY_LABEL = {_label(m): m for ms in MODELS.values() for m in ms}


# ----------------------------------------------------------- compare voices
#
# Pre-rendered audio, not live synthesis: Orpheus runs at ~1.5 tokens/s on
# this Space's CPU, 2.7 minutes per short sentence. make_tts_compare.py builds
# tts_compare.json from the TTS evaluation's own outputs.

_compare_path = ROOT / "tts_compare.json"
try:
    COMPARE = json.loads(_compare_path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError):
    COMPARE = {"languages": {}}
# file key in tts_compare.json -> column heading
COMPARE_COLS = [("human", "Human recording"),
                ("speecht5", "SpeechT5 — the Synthesize tab"),
                ("mms", "MMS-TTS (Meta)"),
                ("orpheus_char", "Orpheus 3B"),
                ("qwen3tts_base", "Qwen3-TTS 1.7B, zero-shot")]
COMPARE_CHOICES = [LANGS[c]["name"] for c in COMPARE["languages"] if c in LANGS]
COMPARE_CLIPS = max((len(v["clips"]) for v in COMPARE["languages"].values()),
                    default=0)


def compare_scores(lang_name):
    s = COMPARE["languages"].get(NAME_TO_CODE.get(lang_name), {}).get("scores", {})
    pct = lambda x: f"{x * 100:.1f} %" if x is not None else "not available"
    sim = lambda x: f"{x:.2f}" if x is not None else "—"
    return (
        "| | round-trip CER ↓ | speaker similarity ↑ |\n|---|---|---|\n"
        f"| Human recording | {pct(s.get('human'))} | — |\n"
        f"| SpeechT5 | {pct(s.get('speecht5'))} | {sim(s.get('speecht5_spk_sim'))} |\n"
        f"| MMS-TTS | {pct(s.get('mms'))} | — |\n"
        f"| **Orpheus 3B** | **{pct(s.get('orpheus'))}** | "
        f"{sim(s.get('orpheus_spk_sim'))} |\n"
        f"| Qwen3-TTS 1.7B, zero-shot (untrained on PLD) | {pct(s.get('qwen3tts_base'))} | "
        f"{sim(s.get('qwen3tts_base_spk_sim'))} |")


def compare_clips(lang_name):
    """Flat list of updates: per clip, the sentence then one audio per column."""
    clips = COMPARE["languages"].get(NAME_TO_CODE.get(lang_name), {}).get("clips", [])
    out = []
    for k in range(COMPARE_CLIPS):
        c = clips[k] if k < len(clips) else None
        out.append(gr.update(value=f"**{k + 1}.** {c['text']}" if c else "",
                             visible=c is not None))
        for key, label in COMPARE_COLS:
            f = (c or {}).get("files", {}).get(key)
            out.append(gr.update(value=str(ROOT / f) if f else None,
                                 label=label if f else f"{label} — not available",
                                 visible=c is not None))
    return out


def _update_kwargs(u):
    """A gr.update() as constructor kwargs, so the first render and every
    later language change go through the same compare_clips()."""
    return {k: v for k, v in u.items() if k != "__type__"}


def _too_big_entry(m):
    size = (f"{m['weights_gib']:.0f} GiB" if m.get("weights_gib")
            else "size unknown")
    cer = f", CER {m['cer'] * 100:.1f}% {m['split']}" if m.get("cer") else ""
    return f"[{m['name']}](https://huggingface.co/{m['repo']}) ({size}{cer})"


def models_for(lang_name):
    return [_label(m) for m in MODELS.get(NAME_TO_CODE.get(lang_name), [])]


def model_note(label):
    """The caveats that belong next to a choice, not buried in a README."""
    m = MODEL_BY_LABEL.get(label)
    if m is None:
        return ""
    bits = [f"[{m['name']}](https://huggingface.co/{m['repo']})",
            f"`{m['licence']}`"]
    if m.get("base_model"):
        bits.append(f"finetuned from `{m['base_model']}`")
    note = " · ".join(bits)
    if m.get("cer"):
        wer = f", WER {m['wer'] * 100:.1f}%" if m.get("wer") else ""
        note += (f"<br>Card reports **CER {m['cer'] * 100:.1f}%**{wer} on the "
                 f"**{m['split']}** split.")
        if m["split"] == "in-domain":
            note += (" That split shares speakers and prompt sentences with "
                     "training, so it reads far better than the model does on "
                     "unfamiliar voices.")
        else:
            note += (" No speaker and no sentence in that split was seen in "
                     "training — the honest number, and the reason it looks "
                     "worse than the in-domain ones.")
    if (m.get("params") or 0) > 500e6:
        note += (f"<br>⚠️ {(m['params']) / 1e9:.1f}B parameters: the first run "
                 f"downloads several GB and CPU inference takes a while.")
    return note


# ---------------------------------------------------------------- model cache

@lru_cache(maxsize=1)
def _torch():
    import torch
    torch.set_num_threads(4)
    return torch


BIG_PARAMS = 500e6          # above this a model gets the single eviction slot


def asr_model(repo: str, kind: str):
    """Two caches, because loading is the expensive part and the models are
    wildly different sizes. Measured on 8 CPU cores, warm disk: a 3.5 s clip
    takes 2-3 s on whisper-small and the 1B CTC heads and 17 s on
    whisper-large-v3, but *loading* them takes 168 s, 230 s and 364 s. So the
    242M baselines stay resident (two of them, ~2 GB total) and the
    multi-gigabyte ones share one slot — switching between two big models
    reloads, switching back to a baseline does not."""
    entry = next((m for ms in MODELS.values() for m in ms
                  if m["repo"] == repo), None)
    big = (entry or {}).get("params") or 0
    return (_big_model if big > BIG_PARAMS else _small_model)(repo, kind)


@lru_cache(maxsize=2)
def _small_model(repo: str, kind: str):
    return _load(repo, kind)


@lru_cache(maxsize=1)
def _big_model(repo: str, kind: str):
    return _load(repo, kind)


def _load(repo: str, kind: str):
    if kind == "ctc":
        from huggingface_hub import hf_hub_download
        from transformers import AutoFeatureExtractor, Wav2Vec2ForCTC
        vocab = json.loads(Path(hf_hub_download(repo, "vocab.json"))
                           .read_text(encoding="utf-8"))
        # the CTC repos carry a vocab.json and a feature extractor, no
        # tokenizer — decoding is ours to do (see ctc_decode)
        return (AutoFeatureExtractor.from_pretrained(repo),
                Wav2Vec2ForCTC.from_pretrained(repo).eval(),
                {i: u for u, i in vocab.items()})
    from transformers import WhisperForConditionalGeneration, WhisperProcessor
    return (WhisperProcessor.from_pretrained(repo),
            WhisperForConditionalGeneration.from_pretrained(repo).eval(), None)


def ctc_decode(ids, id2unit: dict) -> str:
    """Greedy CTC: collapse repeats, drop blanks, join units. Same rule as
    finetune_ctc.py, so the tab reproduces the CER the card reports."""
    out, prev = [], None
    for i in ids:
        i = int(i)
        if i != prev and i != 0:          # 0 is the blank
            out.append(id2unit.get(i, ""))
        prev = i
    return "".join(out).replace(DELIM, " ").strip()


@lru_cache(maxsize=2)
def tts_model(lang: str):
    from transformers import SpeechT5ForTextToSpeech, SpeechT5Processor
    repo = f"{ORG}/speecht5_tts-pld-{lang}"
    return (SpeechT5Processor.from_pretrained(repo),
            SpeechT5ForTextToSpeech.from_pretrained(repo).eval())


@lru_cache(maxsize=1)
def vc_model():
    from transformers import SpeechT5ForSpeechToSpeech, SpeechT5Processor
    repo = f"{ORG}/speecht5_vc-pld"
    return (SpeechT5Processor.from_pretrained(repo),
            SpeechT5ForSpeechToSpeech.from_pretrained(repo).eval())


@lru_cache(maxsize=1)
def vocoder():
    from transformers import SpeechT5HifiGan
    return SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan").eval()


def load_xvector(rel: str):
    return _torch().tensor(np.load(ROOT / rel)).unsqueeze(0)


def as_mono16k(audio):
    """Gradio hands back (sample_rate, np.int16|float array) from mic/upload."""
    if audio is None:
        return None
    sr, data = audio
    data = np.asarray(data)
    if data.ndim > 1:
        data = data.mean(axis=1)
    data = data.astype(np.float32)
    peak = np.abs(data).max()
    if peak > 1.0:                       # int16 range → [-1, 1]
        data = data / 32768.0
    elif peak > 0:
        data = data / max(peak, 1e-9) * 0.95
    if sr != SR:                         # linear resample keeps scipy out of it
        n = int(round(len(data) * SR / sr))
        data = np.interp(np.linspace(0, len(data), n, endpoint=False),
                         np.arange(len(data)), data).astype(np.float32)
    return data


# -------------------------------------------------------------------- actions

def transcribe(lang_name, model_label, audio, reference=""):
    """Returns (text, rating context). The context is what feedback.record
    needs to reconstruct this example later."""
    if audio is None:
        return "Record, upload, or load a preloaded clip first.", None
    wav = as_mono16k(audio)
    if wav is None or len(wav) < SR * 0.2:
        return "That clip is too short to transcribe.", None
    lang = NAME_TO_CODE[lang_name]
    choices = MODELS.get(lang, [])
    entry = MODEL_BY_LABEL.get(model_label) or (choices[0] if choices else None)
    if entry is None:
        return f"No ASR model is registered for {lang_name}.", None
    try:
        torch = _torch()
        proc, model, id2unit = asr_model(entry["repo"], entry["kind"])
        if entry["kind"] == "ctc":
            feats = proc(wav, sampling_rate=SR, return_tensors="pt")
            with torch.no_grad():
                logits = model(**feats).logits
            text = ctc_decode(logits.argmax(-1)[0].tolist(), id2unit)
        else:
            feats = proc.feature_extractor(wav, sampling_rate=SR,
                                           return_tensors="pt").input_features
            with torch.no_grad():
                ids = model.generate(feats, max_new_tokens=200)
            text = proc.batch_decode(ids, skip_special_tokens=True)[0].strip()
    except Exception as e:                # a failed tab must not 500 the Space
        return f"Could not transcribe: {type(e).__name__}: {e}", None

    ctx = {"task": "asr", "language": lang, "model": entry["repo"],
           "units": entry["units"],
           "output_text": text, "reference_text": (reference or "").strip() or None,
           "input_audio": (SR, wav)}
    return text, ctx


def synthesize(lang_name, text, voice_label):
    if not (text or "").strip():
        return None, "Type something to synthesize.", None
    lang = NAME_TO_CODE[lang_name]
    voices = LANGS[lang]["voices"]
    if not voices:
        return None, f"No voice preset for {lang_name}.", None
    pick = next((v for v in voices if voice_label and v["id"] in voice_label),
                voices[0])
    try:
        torch = _torch()
        proc, model = tts_model(lang)
        inputs = proc(text=text.strip(), return_tensors="pt")
        with torch.no_grad():
            speech = model.generate_speech(inputs["input_ids"],
                                           load_xvector(pick["file"]),
                                           vocoder=vocoder())
        out = (SR, speech.numpy())
    except Exception as e:
        return None, f"Could not synthesize: {type(e).__name__}: {e}", None

    ctx = {"task": "tts", "language": lang,
           "model": f"{ORG}/speecht5_tts-pld-{lang}", "voice": pick["id"],
           "input_text": text.strip(), "output_audio": out}
    return out, f"{lang_name} · voice {pick['id']}", ctx


def convert(audio, voice_label):
    if audio is None:
        return None, "Record or upload the audio you want converted.", None
    wav = as_mono16k(audio)
    if wav is None or len(wav) < SR * 0.2:
        return None, "That clip is too short to convert.", None
    if len(wav) > SR * 12:                # keep CPU latency sane
        wav = wav[:SR * 12]
    target = VOICE_INDEX.get(voice_label)
    if target is None:
        return None, "Pick a target voice.", None
    try:
        torch = _torch()
        proc, model = vc_model()
        inputs = proc(audio=wav, sampling_rate=SR, return_tensors="pt")
        with torch.no_grad():
            # The stop token is unreliable on this checkpoint — left alone the
            # decoder runs to the 20x default and babbles well past the end of
            # the utterance. Conversion preserves timing, so bounding output
            # near the input duration is both safe and correct.
            speech = model.generate_speech(inputs["input_values"],
                                           load_xvector(target["file"]),
                                           vocoder=vocoder(),
                                           maxlenratio=VC_MAXLENRATIO)
        out = (SR, speech.numpy())
    except Exception as e:
        return None, f"Could not convert: {type(e).__name__}: {e}", None

    ctx = {"task": "s2s", "model": f"{ORG}/speecht5_vc-pld",
           "language": target.get("language"),   # of the target voice
           "voice": target["id"], "input_audio": (SR, wav),
           "output_audio": out}
    return out, f"Converted to voice {target['id']}", ctx


# ------------------------------------------------------------------- helpers

def sample_choices(lang_name):
    if lang_name not in NAME_TO_CODE:
        return []
    clips = LANGS[NAME_TO_CODE[lang_name]]["clips"]
    return [f"{i + 1}. {c['transcript'][:60]}" for i, c in enumerate(clips)]


def load_sample(lang_name, label):
    """Return the chosen preloaded clip as (sr, data) plus its reference text."""
    import soundfile as sf
    if lang_name not in NAME_TO_CODE:
        return None, ""
    clips = LANGS[NAME_TO_CODE[lang_name]]["clips"]
    if not clips:
        return None, ""
    idx = 0
    if label and label[0].isdigit():
        idx = min(int(label.split(".")[0]) - 1, len(clips) - 1)
    clip = clips[idx]
    data, sr = sf.read(ROOT / clip["file"], dtype="float32")
    return (sr, data), clip["transcript"]


def voices_for(lang_name):
    if lang_name not in NAME_TO_CODE:
        return []
    return [f"{v['id']} ({v['gender']})"
            for v in LANGS[NAME_TO_CODE[lang_name]]["voices"]]


def _feedback_block(what: str):
    """Rate-this-output controls, returned so the caller can wire the state.

    Ratings only leave the browser when someone clicks, and the audio
    checkbox is shown next to the buttons rather than buried in a policy
    paragraph — people are sending us their own voice recordings.
    """
    import feedback

    with gr.Accordion(f"Was this {what} any good?", open=False):
        if feedback.enabled():
            gr.Markdown(
                f"Ratings train the next round of models. They are stored in a "
                f"**private** dataset (`{feedback.DETAIL}`) together with the "
                f"text, and with the audio if you leave the box ticked.")
        else:
            gr.Markdown(
                f"⚠️ Ratings are **not being saved** — {feedback.DETAIL}. The "
                f"buttons still work so you can see the flow.")
        comment = gr.Textbox(label="Anything to add? (optional)",
                             placeholder="e.g. wrong word, robotic prosody, "
                                         "clipped ending",
                             lines=1)
        keep = gr.Checkbox(value=True, label="Include the audio")
        with gr.Row():
            good = gr.Button("👍 Good", size="sm")
            bad = gr.Button("👎 Needs work", size="sm")
        status = gr.Markdown("")
    return comment, keep, good, bad, status


def _wire_feedback(state, comment, keep, good, bad, status):
    import feedback

    def rate(kind):
        def _fn(ctx, note, keep_audio):
            return feedback.record(kind, ctx, note, keep_audio)
        return _fn

    good.click(rate("good"), [state, comment, keep], status)
    bad.click(rate("bad"), [state, comment, keep], status)


# ----------------------------------------------------------------------- ui

def build_tabs():
    """Add the three demo tabs to the enclosing gr.Blocks context."""
    if not LANGS:
        with gr.Tab("🎙️ Speech demo"):
            gr.Markdown("Demo assets are missing from this Space "
                        "(`assets.json`), so the speech tabs are unavailable.")
        return

    # API-only: lets the Space's feedback wiring be checked from outside
    # without clicking through the UI, since a misnamed secret fails silently.
    import feedback as _fb
    _status_btn = gr.Button("feedback status", visible=False)
    _status_out = gr.Textbox(visible=False)
    _status_btn.click(_fb.status_report, None, _status_out,
                      api_name="feedback_status")

    with gr.Tab("🎙️ Transcribe"):
        _n_models = sum(len(v) for v in MODELS.values())
        gr.Markdown(
            f"Record yourself, upload a file, or load a preloaded clip. "
            f"**{_n_models} models** are on offer across the ten languages: "
            f"the whisper-small baselines, and for Cebuano and Kapampangan the "
            f"bake-off entries — whisper-large-v3 and the Omnilingual 1B "
            f"encoder with a CTC head over characters or syllables. Pick one "
            f"per language and compare them on the same clip. **The first run "
            f"of a model downloads and loads it — 1 GB for whisper-small, up "
            f"to 6 GB for large-v3, minutes either way. After that a clip "
            f"takes seconds** (the CTC models are the quickest: one forward "
            f"pass, no autoregressive decoding).")
        if TOO_BIG:
            gr.Markdown("Also trained, but too large for this free CPU Space: "
                        + "; ".join(_too_big_entry(m) for m in TOO_BIG) + ".")
        with gr.Row():
            with gr.Column():
                a_lang = gr.Dropdown(CHOICES, value=DEFAULT, label="Language")
                _m = models_for(DEFAULT)
                a_model = gr.Dropdown(_m, value=_m[0] if _m else None,
                                      label="Model")
                a_note = gr.Markdown(model_note(_m[0] if _m else ""))
                a_sample = gr.Dropdown(sample_choices(DEFAULT),
                                       label="Preloaded clip (optional)")
                a_load = gr.Button("Load preloaded clip")
                a_audio = gr.Audio(sources=["microphone", "upload"],
                                   type="numpy", label="Audio")
            with gr.Column():
                a_ref = gr.Textbox(label="Reference transcript (preloaded clip)",
                                   interactive=False)
                a_out = gr.Textbox(label="Model transcription", lines=4)
                a_go = gr.Button("Transcribe", variant="primary")
                a_state = gr.State(None)
                a_fb = _feedback_block("transcription")

        def _on_lang(lang_name):
            ms = models_for(lang_name)
            return (gr.update(choices=sample_choices(lang_name), value=None),
                    gr.update(choices=ms, value=ms[0] if ms else None),
                    model_note(ms[0] if ms else ""))

        a_lang.change(_on_lang, a_lang, [a_sample, a_model, a_note])
        a_model.change(model_note, a_model, a_note)
        a_load.click(load_sample, [a_lang, a_sample], [a_audio, a_ref])
        a_go.click(transcribe, [a_lang, a_model, a_audio, a_ref],
                   [a_out, a_state])
        _wire_feedback(a_state, *a_fb)

    with gr.Tab("🔊 Synthesize"):
        gr.Markdown(
            "Type text in the chosen language and hear it spoken by one of "
            "that language's speakers. Write numbers as words — the training "
            "text contains no verbalized numerals.")
        with gr.Row():
            with gr.Column():
                t_lang = gr.Dropdown(CHOICES, value=DEFAULT, label="Language")
                _v = voices_for(DEFAULT)
                t_voice = gr.Dropdown(_v, value=_v[0] if _v else None,
                                      label="Voice")
                t_text = gr.Textbox(label="Text", lines=3,
                                    value="Maayong buntag sa tanan.")
                t_go = gr.Button("Synthesize", variant="primary")
            with gr.Column():
                t_audio = gr.Audio(label="Synthesized speech")
                t_note = gr.Textbox(label="Details", interactive=False)
                t_state = gr.State(None)
                t_fb = _feedback_block("synthesis")

        t_lang.change(
            lambda l: gr.update(choices=voices_for(l),
                                value=(voices_for(l) or [None])[0]),
            t_lang, t_voice)
        t_go.click(synthesize, [t_lang, t_text, t_voice],
                   [t_audio, t_note, t_state])
        _wire_feedback(t_state, *t_fb)

    if COMPARE_CHOICES:
        with gr.Tab("🎧 Compare voices"):
            gr.Markdown(
                "The same sentences, spoken by a person and by each TTS "
                "system. **Orpheus 3B** (9 languages) is the org's newest TTS "
                "and the most intelligible by a wide margin — but at ~2.7 "
                "minutes per sentence on this Space's CPU it cannot run live "
                "here, so these clips were generated offline with the "
                "evaluation's own settings.\n\n"
                "**How to read the scores.** Each system spoke the same 50 "
                "sentences per language, from recordings held out of "
                "training; an ASR judge transcribed the audio and CER is "
                "measured against the text. The human row is the judge's own "
                "floor. Every number in a table came from the same judge. "
                "Caveats: 50 sentences cannot resolve a one-point gap; the "
                "judges are our own ASR models, trained on the same corpus, so "
                "an independent judge is still owed; and the sentences' "
                "*text* can recur in training (the corpus reuses prompts) even "
                "though the recordings do not. Orpheus conditions on a speaker "
                "label rather than cloning a voice, which is why its speaker "
                "similarity is the lower one.")
            _cdef = ("Cebuano" if "Cebuano" in COMPARE_CHOICES
                     else COMPARE_CHOICES[0])
            c_lang = gr.Dropdown(COMPARE_CHOICES, value=_cdef, label="Language")
            c_scores = gr.Markdown(compare_scores(_cdef))
            c_outputs = []
            _init = compare_clips(_cdef)
            for k in range(COMPARE_CLIPS):
                base = k * (1 + len(COMPARE_COLS))
                c_outputs.append(gr.Markdown(**_update_kwargs(_init[base])))
                with gr.Row():
                    for j, _ in enumerate(COMPARE_COLS):
                        c_outputs.append(gr.Audio(
                            interactive=False,
                            **_update_kwargs(_init[base + 1 + j])))
            c_lang.change(lambda l: [compare_scores(l)] + compare_clips(l),
                          c_lang, [c_scores] + c_outputs)

    with gr.Tab("🎭 Convert voice"):
        gr.Markdown(
            "Say something and hear it in another speaker's voice. One model "
            "covers all ten languages: it was trained on pairs of different "
            "speakers reading the *same* sentence, which the corpus provides "
            "because its prompt lists are shared across speakers.")
        with gr.Row():
            with gr.Column():
                v_audio = gr.Audio(sources=["microphone", "upload"],
                                   type="numpy",
                                   label="Your audio (any language)")
                v_target = gr.Dropdown(
                    VOICE_LABELS,
                    value=VOICE_LABELS[0] if VOICE_LABELS else None,
                    label="Target voice")
                v_go = gr.Button("Convert", variant="primary")
            with gr.Column():
                v_out = gr.Audio(label="Converted speech")
                v_note = gr.Textbox(label="Details", interactive=False)
                v_state = gr.State(None)
                v_fb = _feedback_block("conversion")
        v_go.click(convert, [v_audio, v_target], [v_out, v_note, v_state])
        _wire_feedback(v_state, *v_fb)
